# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.3    

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name : Checkout
      uses: actions/checkout@v2
    
    # Navigate to project files and create makefile
    - name: Run qmake
      run: cd Dnd-Combat-Tracker && qmake
    
    # Navigate to project files and compile program
    - name: Run make
      run: cd Dnd-Combat-Tracker && make 

    # Confirm if it passed/failed
    - name: it worked
      run: testscript
